# Generated by Django 5.0.1 on 2024-01-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("details", models.CharField(max_length=200)),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now=True)),
                ("price_total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price_discount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "price_recurency",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("type_recurency", models.CharField(max_length=10)),
                ("observation", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.category",
                    ),
                ),
            ],
        ),
    ]
