# Generated by Django 5.0.1 on 2024-01-13 17:01

import cpf_field.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('nickname', models.CharField(max_length=15, verbose_name='Apelido')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='Celular')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('location', models.CharField(max_length=100, verbose_name='Endereço')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('region', models.CharField(max_length=80, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('date_birth', models.DateField(verbose_name='Data de nascimento')),
                ('photo_perfil', models.ImageField(upload_to='person')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='observation',
            field=models.CharField(max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço com desconto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_recurency',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço recorrente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço normal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_recurency',
            field=models.CharField(max_length=10, verbose_name='Tipo de recorrência'),
        ),
    ]
