# Generated by Django 5.0.1 on 2024-01-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_person_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="cpf",
        ),
        migrations.AddField(
            model_name="person",
            name="document_number",
            field=models.CharField(
                default="", max_length=20, verbose_name="Numero documento"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="document_type",
            field=models.CharField(
                default="CPF", max_length=5, verbose_name="Tipo documento"
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=20, verbose_name="Metodo de pagamento"),
                ),
                (
                    "payed_status",
                    models.CharField(max_length=10, verbose_name="Status pagamento"),
                ),
                (
                    "installments",
                    models.CharField(max_length=2, verbose_name="Numero de parcelas"),
                ),
                (
                    "id_checkout_payment",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Id pagamento"
                    ),
                ),
                (
                    "amount_payed",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Valor total"
                    ),
                ),
                ("date_payment", models.DateField(verbose_name="Data pagamento")),
                (
                    "last_for_digits_card",
                    models.CharField(
                        max_length=4, verbose_name="Ultimos 4 digitos do cartão"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.person",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
        ),
    ]
