# Generated by Django 5.0.1 on 2024-01-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_person_cpf_person_document_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_birth",
            field=models.DateField(null=True, verbose_name="Data de nascimento"),
        ),
    ]
