# Generated by Django 5.0.1 on 2024-01-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_person_date_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_birth",
            field=models.DateTimeField(null=True, verbose_name="Data de nascimento"),
        ),
    ]
