# Generated by Django 5.0.1 on 2024-01-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_person_date_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_payment",
            field=models.DateTimeField(verbose_name="Data pagamento"),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_birth",
            field=models.DateField(null=True, verbose_name="Data de nascimento"),
        ),
    ]
