# Generated by Django 5.0.1 on 2024-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_person_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_checkout_payment',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Id pagamento'),
        ),
    ]
