# Generated by Django 5.0.1 on 2024-01-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_order_id_checkout_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id_checkout_payment",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Id pagamento"
            ),
        ),
    ]
