# Generated by Django 5.0.1 on 2024-02-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_id_checkout_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="link_checkout",
            field=models.CharField(
                default="", max_length=200, verbose_name="Link do pagamento"
            ),
        ),
    ]
