# Generated by Django 5.0.1 on 2024-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsform",
            name="leadsource",
            field=models.CharField(
                choices=[
                    ("Landing Page", "Landing Page"),
                    ("Portal admin", "Portal admin"),
                ],
                max_length=20,
                verbose_name="Origem cadastro",
            ),
        ),
        migrations.AlterField(
            model_name="leadsform",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="leadsform",
            name="phone",
            field=models.CharField(max_length=16, unique=True, verbose_name="Celular"),
        ),
    ]
