# Generated by Django 5.0.1 on 2024-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landingpage",
            "0002_alter_leadsform_leadsource_alter_leadsform_nome_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsform",
            name="email",
            field=models.EmailField(max_length=200, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="leadsform",
            name="phone",
            field=models.CharField(max_length=16, verbose_name="Celular"),
        ),
    ]
