# Generated by Django 5.0.1 on 2024-01-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0004_preinscricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preinscricao",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
